dist: trusty
language: clojure

services:
  - docker

stages:
  - build

env:
  global:
    - DOCKER_USERNAME: domaindrivenarchitecture
    - secure: "BBnpv1SF+SGa+lEVkvBQ+7DKSNWa5yV1HUnwkUy4JzLhWDhdo8knLI1kH8Ci36UsWGkd3aAZnCUOmKR01fui8ct9tEV7Lt02KOAEKfCZ4z6kow2+0/JgqhiGS1+JK6NgAx6M4O3++My2ZgMLDylAjBJC4MAjVwZLtN5eHdGQKwf34pORZNWgx2xqMKNWncijfoRICJfWKNvAm1YccTUkyR0Rwf2wjCNxHfRpntJxBV9h+J4Lm77Y2V9DdyEPOGkT1D6PRvhIe/1yYJDxO5sU2ecr1ARaahhT8yO1LEI0fBKi2s5tWlgVPa5B9K4gInEMo4kFaXeFeRBQHKLBm657sHXJcR+aWxjbncHlT4Hp2Rtsn33CEWdPRoWhdMmRK5sk0bhX4C8KHnHdLmlbDjMcEFUKfL27D4lpFCujru1thtCXUZU17XJ4Ln/PwT1P/K+BiqXZqu+f9yzvjg1vQFirHtoeArpIgEZHzvMPMlw7pmaVrItyG0OnrkL/AbP3DNavFlsBCf+434h4kPRYUw+BY6L5SxTulZyDnibwZz8EfXCpUCrjquzCfsUeE9r9u6XOX4j6azGFUAmvtIyk2Hky58yKAeRWdDZqN5oBUvljTjdknsUQPKHOWTQ1khFM3FJohggZG9yQxYMicH2m99QgDNb3QNBIChn6SduqYBnRKb4="

jobs:
  include:
    - stage: build
      language: clojure
      script:
        - lein test
        - lein uberjar
        - md5sum target/uberjar/dda-git-standalone.jar > target/uberjar/dda-git-standalone.jar.md5
        - # create docker image
        - docker build -t dda-git-crate --file integration/docker/synced_repo/image/Dockerfile .
        - # integration test on docker image level
        - docker build -t dda-git-crate-test --file integration/docker/synced_repo/test/Dockerfile .
      deploy:
        - provider: releases
          skip_cleanup: true
          on:
            tags: true
          api_key:
            secure: "i52VCwtwL5gZEPJ7B5ELtKUmjc1GqdHBLE04fuveDSGt9iMniwjn+UvntBtkBmp39o2/qXWizhAZSsYsqIo9MWpXg+HtyqTtgfhkFPOKAeyPWRgYM13QKB5X0cjjVPAtDLqcdIBk7lFcXDFnciXOAYKBz8Sn8L3zDyDIwRkLsN8oBDIrj+7yg+LMJg80wBM591mc34sDR3xrfCqgFKgJB7ATB9UttKdX5UeCzeMG2cP4vwc1KjVUBaqy/BIvKHmoS5TxP3uBCjxStsF8AwaocPAXXTjV/NS5+QIIeBXrAeuTtWxRNuNRlSakpeQUa6MdpnyE35u+pJiObflDzYr34gDHjR5HgZ0Qbu/nQMaKirahFfRHkfAfcm/wqOS7SjQHzo1kjm2HOeQO+nKoagnepALs8tElE/2EZUkFhBfHpheLtmIV2AqyrjKshgLk6M5wojsaFKn2ujQ4v54dvREVuHzeQPoxEEy4ymYSOvTB8vvkLflyeBL9JGJDnBT5PpQrpXpB0MKQtp8muxLuu8pbhhV/gA4H0y1MJP09trRPWsjOqzxMdJkGOVzpsUKdIXn9PNitbavZbCl7GP4+gJH+P7NI1krbUFctj9jVYOZvvqlx/t0mxdcsaET57iVqkHF8W4rolktRHjne++m99IdNIoIj/nFD1SUL/bn4MCADJp4="
          file:
            - target/uberjar/dda-git-standalone.jar
            - target/uberjar/dda-git-standalone.jar.md5
