sudo: required
dist: trusty

matrix:
  include:
    - language: clojure
    - language: python
      python:
        - "3.6"
      install:
        - pip install docker
      script:
        - echo $(python --version)
        - echo $(pip --version)
        - echo $(python3 --version)
        - echo $(pip3 --version)
