sudo: required

language: clojure

services:
  - docker

stages:
  - provide_docker
  - integrationtest

script:
  - lein test
  - lein uberjar

jobs:
  include:
    - stage: provide_docker
      install:
        - echo "ommit install"
      script:
        - docker build -t dda/dda-git-crate .
    - stage: integrationtest
      install:
        - echo "ommit install"
      script:
        - echo "test it"
