sudo: required

language: clojure

services:
  - docker

stages:
  - build
  - integrationtest

jobs:
  include:
    - stage: build
      script:
        - lein test
        - lein uberjar
        - docker build -t dda/dda-git-crate .
    - stage: integrationtest
      install:
        - echo "ommit install"
      script:
        - echo "test it"
