dist: trusty
language: clojure

services:
  - docker

stages:
  - build

env:
  global:
    - DOCKER_USERNAME: domaindrivenarchitecture
    - secure: "BBnpv1SF+SGa+lEVkvBQ+7DKSNWa5yV1HUnwkUy4JzLhWDhdo8knLI1kH8Ci36UsWGkd3aAZnCUOmKR01fui8ct9tEV7Lt02KOAEKfCZ4z6kow2+0/JgqhiGS1+JK6NgAx6M4O3++My2ZgMLDylAjBJC4MAjVwZLtN5eHdGQKwf34pORZNWgx2xqMKNWncijfoRICJfWKNvAm1YccTUkyR0Rwf2wjCNxHfRpntJxBV9h+J4Lm77Y2V9DdyEPOGkT1D6PRvhIe/1yYJDxO5sU2ecr1ARaahhT8yO1LEI0fBKi2s5tWlgVPa5B9K4gInEMo4kFaXeFeRBQHKLBm657sHXJcR+aWxjbncHlT4Hp2Rtsn33CEWdPRoWhdMmRK5sk0bhX4C8KHnHdLmlbDjMcEFUKfL27D4lpFCujru1thtCXUZU17XJ4Ln/PwT1P/K+BiqXZqu+f9yzvjg1vQFirHtoeArpIgEZHzvMPMlw7pmaVrItyG0OnrkL/AbP3DNavFlsBCf+434h4kPRYUw+BY6L5SxTulZyDnibwZz8EfXCpUCrjquzCfsUeE9r9u6XOX4j6azGFUAmvtIyk2Hky58yKAeRWdDZqN5oBUvljTjdknsUQPKHOWTQ1khFM3FJohggZG9yQxYMicH2m99QgDNb3QNBIChn6SduqYBnRKb4="

jobs:
  include:
    - stage: build
      language: clojure
      script:
        - lein test
        - lein uberjar
        - md5sum target/dda-git-standalone.jar > target/dda-git-standalone.jar.md5
        - # create docker image
        - docker build -t dda-git-crate --file integration/docker/synced_repo/image/Dockerfile .
        - # integration test on docker image level
        - docker build -t dda-git-crate-test --file integration/docker/synced_repo/test/Dockerfile .
      deploy:
        skip_cleanup: true
        - provider: releases
          overwrite: true
          draft: true
          api_key:
            secure: "m86pn7NJtpPuC8wdD53KvShCSEtcWUVUIgWYlqQh4TT17Rs8LI6AwoQ4oZlPVr5ZITsD01vvT05BMp8TSFa9L2fvMoAgNX2d9Rlnh7CwjQr8BU40HjaslLozyxIBCerjehaufzBpEHaoPKtjQR0/p2DNACt1d504Uv6JlCZ8UIkUwDJl6CjO/L5wtk2IEFKen8wk+/B9Oa7UB0V4mrxzzwjFQWJQsud/lV+Ti71aZISSrxnLSAx6oAe727oU9/WP94d2hbZ9FmnHyzXLYrD+G6coHh/mm3+VVyhjq8KR6BgrfhJmoR7DjSXgCsV/FxSCByu/pc1O8CGLx5V/iMf4DnF0Mcrt9MNijsV0QqZ3pFBq1S2PkCa1F+StZY3khkfVW1AlHGQJdiZezst1FfJZs7rfiSqC96E+5QAyUV57IlJoRWRfFXU38Gt5zsT+bd2Eu1lIVBx71wcEF0prZJkYkyyUbayZTFC9XTe9x3uIZVI6VbBwL/biOXz7RBbXFg69mmwZLXbQymUMDs58XlUvps1PWwdDF7wlU1ANBxHZ9SxrU4N2/5BnSXNGdA5hKM8viuh6hMl4nCRCgMJKsvhD/dAvdU1HbvQkAEs6WRlo03gk6bCb5xxfAzcSf+UQTYmmttVvkFft8mih2w9xZDVIvFvzZkydLeTe/zOuq/3iTOg="
          file:
            - target/dda-git-standalone.jar
            - target/dda-git-standalone.jar.md5
        - provider: script
          script: bash integration/docker/publish.sh dda-git-crate
